name = "Multiscale model microenvironmental roles breast cancer"
uuid = ""
authors = ["jrromeroarias"]
version = "1.23.10"

[deps]
#DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
#LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
#Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
#Plots
#PyPlot
#Compat
#Distributions
#ProgressMeter 
#Random
#CSV 
#DataFrames 

[compat]
#DataStructures = "0.18"
julia = "1.6"

[extras]
#Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
#test = ["Test"]
